# syntax=docker/dockerfile:1

ARG NODE_REGISTRY=docker.io
ARG NGINX_REGISTRY=docker.io

FROM ${NODE_REGISTRY}/library/node:20-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
ARG NPM_REGISTRY=https://registry.npmjs.org
RUN npm config set registry "$NPM_REGISTRY" && npm ci

COPY . .
RUN npm run build

FROM ${NGINX_REGISTRY}/library/nginx:alpine AS runtime
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 8080
